/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WordsIndexImport } from './routes/words/index'
import { Route as TodosIndexImport } from './routes/todos/index'
import { Route as WordsWordImport } from './routes/words/$word'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WordsIndexRoute = WordsIndexImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => rootRoute,
} as any)

const TodosIndexRoute = TodosIndexImport.update({
  id: '/todos/',
  path: '/todos/',
  getParentRoute: () => rootRoute,
} as any)

const WordsWordRoute = WordsWordImport.update({
  id: '/words/$word',
  path: '/words/$word',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/words/$word': {
      id: '/words/$word'
      path: '/words/$word'
      fullPath: '/words/$word'
      preLoaderRoute: typeof WordsWordImport
      parentRoute: typeof rootRoute
    }
    '/todos/': {
      id: '/todos/'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosIndexImport
      parentRoute: typeof rootRoute
    }
    '/words/': {
      id: '/words/'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/words/$word': typeof WordsWordRoute
  '/todos': typeof TodosIndexRoute
  '/words': typeof WordsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/words/$word': typeof WordsWordRoute
  '/todos': typeof TodosIndexRoute
  '/words': typeof WordsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutLazyRoute
  '/words/$word': typeof WordsWordRoute
  '/todos/': typeof TodosIndexRoute
  '/words/': typeof WordsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/words/$word' | '/todos' | '/words'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/words/$word' | '/todos' | '/words'
  id: '__root__' | '/' | '/about' | '/words/$word' | '/todos/' | '/words/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutLazyRoute: typeof AboutLazyRoute
  WordsWordRoute: typeof WordsWordRoute
  TodosIndexRoute: typeof TodosIndexRoute
  WordsIndexRoute: typeof WordsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutLazyRoute: AboutLazyRoute,
  WordsWordRoute: WordsWordRoute,
  TodosIndexRoute: TodosIndexRoute,
  WordsIndexRoute: WordsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/words/$word",
        "/todos/",
        "/words/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/words/$word": {
      "filePath": "words/$word.tsx"
    },
    "/todos/": {
      "filePath": "todos/index.tsx"
    },
    "/words/": {
      "filePath": "words/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
